name: login_logout
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:

  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  starlight_utils:
      git:
        url: https://github.com/YeMyoAung/starlight_utils.git
  flutter:
    sdk: flutter
  get_it: ^7.6.6
  flutter_bloc: ^8.1.3
  firebase_storage: ^11.6.4

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
