name: login_logout
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:

  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  starlight_utils:
      git:
        url: https://github.com/YeMyoAung/starlight_utils.git
  flutter:
  
    sdk: flutter
  get_it: ^7.6.6
  flutter_bloc: ^8.1.3
  firebase_storage: ^11.6.4
  image_picker: ^0.8.9
  rich_editor: ^0.0.8
  cloud_firestore: ^4.15.3
  flutter_widget_from_html: ^0.14.11
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
   
   